name: CheckScript

on:
  push:
    branches-ignore:
      - 'private*'
    paths:
      - 'scripts/**'
      - 'dependencies.gradle.kts'
  pull_request:
    paths:
      - 'scripts/**'
      - 'dependencies.gradle.kts'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v2
        with:
          path: |
            libs
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: deps-${{ hashFiles('dependencies.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            deps-

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/cache@v2
        with:
          path: |
            scripts/cache
          key: kts-cache-${{ steps.date.outputs.date }}
          restore-keys: |
            kts-cache

      # Runs a single command using the runners shell
      - name: Run gradle build
        run: ./gradlew precompile
